version: '2'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    links:
      - godoc
    command: "echo hello world"
  godoc:
    build:
      context: .
      dockerfile: Dockerfile-godoc
    ports:
      - "6060:6060"
    command: "godoc -http=:6060"
  kong-database:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
  kong:
    image: mashape/kong
    depends_on:
      - kong-database
    environment:
      DATABASE: postgres
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
